# With some help from: https://gist.github.com/dgerosa/2e1f47a39180f39bde848e38243efa94

name: build
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      latex: ${{ steps.filter.outputs.latex }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            latex:
              - '**.tex'
              - '**.bib'
  build:
    needs: check
    if: needs.check.outputs.latex == 'true'
    runs-on: ubuntu-latest
    env:
      DIR: .
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile cv.tex
        uses: dante-ev/latex-action@latest
        with:
          root_file: cv
          working_directory: ${{ env.DIR }}
      - name: Compile cv_en.tex
        uses: dante-ev/latex-action@latest
        with:
          root_file: cv_en
          working_directory: ${{ env.DIR }}
      - name: move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/cv.pdf ${{ env.DIR }}/cv_en.pdf ./github_artifacts/
      - name: Upload cv.pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv.pdf
          path: ./github_artifacts/cv.pdf
      - name: Upload cv_en.pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv_en.pdf
          path: ./github_artifacts/cv_en.pdf
  deploy:
    needs: [check, build]
    if: needs.check.outputs.latex == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
          enable_jekyll: true
  copy-index-to-build:
    needs: [check, deploy]
    if: always() && needs.check.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.3
        env:
          key: main
          files: index.html CNAME icons/* en/index.html es/index.html
